param(
    [string]$ConfigPath = "configs/weekly_mof_latest.json",
    [string]$TaskName = "MOF Literature Weekly",
    [string]$Weekday = "",
    [string]$Time = "",
    [string]$PythonExe = "python",
    [switch]$Force
)

$ErrorActionPreference = "Stop"

function Resolve-ConfigValue {
    param(
        [Parameter(Mandatory = $true)]
        [string]$BasePath,
        [Parameter(Mandatory = $true)]
        [string]$ConfigValue
    )

    if ([System.IO.Path]::IsPathRooted($ConfigValue)) {
        return (Resolve-Path $ConfigValue).Path
    }
    return (Resolve-Path (Join-Path $BasePath $ConfigValue)).Path
}

function Convert-Weekday {
    param([Parameter(Mandatory = $true)][string]$Value)

    switch ($Value.ToUpperInvariant()) {
        "MON" { return [System.DayOfWeek]::Monday }
        "TUE" { return [System.DayOfWeek]::Tuesday }
        "WED" { return [System.DayOfWeek]::Wednesday }
        "THU" { return [System.DayOfWeek]::Thursday }
        "FRI" { return [System.DayOfWeek]::Friday }
        "SAT" { return [System.DayOfWeek]::Saturday }
        "SUN" { return [System.DayOfWeek]::Sunday }
        "MONDAY" { return [System.DayOfWeek]::Monday }
        "TUESDAY" { return [System.DayOfWeek]::Tuesday }
        "WEDNESDAY" { return [System.DayOfWeek]::Wednesday }
        "THURSDAY" { return [System.DayOfWeek]::Thursday }
        "FRIDAY" { return [System.DayOfWeek]::Friday }
        "SATURDAY" { return [System.DayOfWeek]::Saturday }
        "SUNDAY" { return [System.DayOfWeek]::Sunday }
        default { throw "Unsupported weekday value: $Value" }
    }
}

$repoRoot = $PSScriptRoot
$resolvedConfig = Resolve-ConfigValue -BasePath $repoRoot -ConfigValue $ConfigPath
$configDir = Split-Path -Parent $resolvedConfig
$config = Get-Content -Path $resolvedConfig -Raw | ConvertFrom-Json

if ([string]::IsNullOrWhiteSpace($Weekday)) {
    $Weekday = if ($config.schedule.weekday) { [string]$config.schedule.weekday } else { "MON" }
}
if ([string]::IsNullOrWhiteSpace($Time)) {
    $Time = if ($config.schedule.time) { [string]$config.schedule.time } else { "09:00" }
}

$runScript = (Resolve-Path (Join-Path $PSScriptRoot "run_weekly.ps1")).Path
$actionArgs = "-ExecutionPolicy Bypass -File `"$runScript`" -ConfigPath `"$resolvedConfig`" -PythonExe `"$PythonExe`""
$action = New-ScheduledTaskAction -Execute "powershell.exe" -Argument $actionArgs -WorkingDirectory $repoRoot
$trigger = New-ScheduledTaskTrigger -Weekly -DaysOfWeek (Convert-Weekday -Value $Weekday) -At $Time
$settings = New-ScheduledTaskSettingsSet -StartWhenAvailable -MultipleInstances IgnoreNew
$userId = "$env:USERDOMAIN\$env:USERNAME"
$principal = New-ScheduledTaskPrincipal -UserId $userId -LogonType Interactive -RunLevel Limited

if ($Force -and (Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue)) {
    Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false
}

Register-ScheduledTask -TaskName $TaskName -Action $action -Trigger $trigger -Settings $settings -Principal $principal -Description "Weekly MOF literature update generated by literature_tool." | Out-Null
Write-Host "Registered scheduled task '$TaskName' for $Weekday at $Time using $resolvedConfig"
