param(
    [string]$TaskName = "MOF Method Transfer Novelty Weekly",
    [string]$Weekday = "MON",
    [string]$Time = "10:30",
    [string]$PythonExe = "python",
    [ValidateSet("Interactive", "S4U")]
    [string]$LogonType = "Interactive",
    [switch]$WakeToRun,
    [switch]$Force
)

$ErrorActionPreference = "Stop"

function Convert-Weekday {
    param([Parameter(Mandatory = $true)][string]$Value)

    switch ($Value.ToUpperInvariant()) {
        "MON" { return [System.DayOfWeek]::Monday }
        "TUE" { return [System.DayOfWeek]::Tuesday }
        "WED" { return [System.DayOfWeek]::Wednesday }
        "THU" { return [System.DayOfWeek]::Thursday }
        "FRI" { return [System.DayOfWeek]::Friday }
        "SAT" { return [System.DayOfWeek]::Saturday }
        "SUN" { return [System.DayOfWeek]::Sunday }
        "MONDAY" { return [System.DayOfWeek]::Monday }
        "TUESDAY" { return [System.DayOfWeek]::Tuesday }
        "WEDNESDAY" { return [System.DayOfWeek]::Wednesday }
        "THURSDAY" { return [System.DayOfWeek]::Thursday }
        "FRIDAY" { return [System.DayOfWeek]::Friday }
        "SATURDAY" { return [System.DayOfWeek]::Saturday }
        "SUNDAY" { return [System.DayOfWeek]::Sunday }
        default { throw "Unsupported weekday value: $Value" }
    }
}

$repoRoot = $PSScriptRoot
$runScript = (Resolve-Path (Join-Path $PSScriptRoot "run_method_transfer_novelty.ps1")).Path
$actionArgs = "-ExecutionPolicy Bypass -File `"$runScript`" -PythonExe `"$PythonExe`""
$action = New-ScheduledTaskAction -Execute "powershell.exe" -Argument $actionArgs -WorkingDirectory $repoRoot
$trigger = New-ScheduledTaskTrigger -Weekly -DaysOfWeek (Convert-Weekday -Value $Weekday) -At $Time
$settings = New-ScheduledTaskSettingsSet `
    -StartWhenAvailable `
    -AllowStartIfOnBatteries `
    -DontStopIfGoingOnBatteries `
    -MultipleInstances IgnoreNew `
    -WakeToRun:$WakeToRun
$userId = "$env:USERDOMAIN\$env:USERNAME"
$principal = New-ScheduledTaskPrincipal -UserId $userId -LogonType $LogonType -RunLevel Limited
$description = "Weekly method-transfer novelty workflow generated by literature_tool."

if ($Force -and (Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue)) {
    Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false
}

Register-ScheduledTask -TaskName $TaskName -Action $action -Trigger $trigger -Settings $settings -Principal $principal -Description $description | Out-Null
Write-Host "Registered scheduled task '$TaskName' for $Weekday at $Time using run_method_transfer_novelty.ps1 (logon=$LogonType, wake=$WakeToRun)"
